Also redirect stderr to /dev/null when checking for backend
ncopa/lddtree pull request #6
Opened 2017-03-14 15:41 UTC by Luthaf

Without this change:

```
which: no scanelf in (~/bin:/opt/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin)
ls => /bin/ls (interpreter => /lib64/ld-linux-x86-64.so.2)
    libselinux.so.1 => /lib64/libselinux.so.1
        libpcre.so.1 => /lib64/libpcre.so.1
            libpthread.so.0 => /lib64/libpthread.so.0
        libdl.so.2 => /lib64/libdl.so.2
    libcap.so.2 => /lib64/libcap.so.2
        libattr.so.1 => /lib64/libattr.so.1
    libacl.so.1 => /lib64/libacl.so.1
    libc.so.6 => /lib64/libc.so.6
```

With this change:

```
ls => /bin/ls (interpreter => /lib64/ld-linux-x86-64.so.2)
    libselinux.so.1 => /lib64/libselinux.so.1
        libpcre.so.1 => /lib64/libpcre.so.1
            libpthread.so.0 => /lib64/libpthread.so.0
        libdl.so.2 => /lib64/libdl.so.2
    libcap.so.2 => /lib64/libcap.so.2
        libattr.so.1 => /lib64/libattr.so.1
    libacl.so.1 => /lib64/libacl.so.1
    libc.so.6 => /lib64/libc.so.6
```

2017-03-14 16:25 UTC, ncopa requested changes

2017-03-14 16:25 UTC, ncopa commented on lddtree.sh
> +if which scanelf &>/dev/null; then
i think the `&>/dev/null` is bashism and not POSIX shell. We should probably do `>/dev/null 2>&1`

2017-03-14 16:25 UTC, ncopa commented on lddtree.sh
> +elif which objdump &>/dev/null && which readelf &>/dev/null; then
Same here. Change to `>/dev/null 2>&1`

2017-03-14 20:28 UTC, Luthaf commented
Done !

2017-03-20 22:53 UTC, Luthaf commented
ping ?

2017-03-22 11:11 UTC, merged

2017-03-22 14:16 UTC, ncopa commented
thank you